/*
 * Kári Snær Kárason - ksk12@hi.is
 * JuggleQuest lokaverkefni - 10/04/2016
 * 
 * Þessi klasi birtir upplýsingar um hvernig á að spila leikinn. Á hann er kallað
 * bæði úr MainMenu klasanum og AdalGluggi klasanum.
 */
package is.hi.Lokaverkefni.vidmot;

/**
 *
 * @author Kári
 */
public class Instructions extends javax.swing.JDialog {

    /**
     * Creates new form Instructions
     */
    public Instructions(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        instrPanel = new javax.swing.JPanel();
        instr2 = new javax.swing.JLabel();
        instr4 = new javax.swing.JLabel();
        instr3 = new javax.swing.JLabel();
        instrHeader = new javax.swing.JLabel();
        gotItBtn = new javax.swing.JButton();
        instr1 = new javax.swing.JLabel();
        instr5 = new javax.swing.JLabel();
        instr6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(522, 414));
        setMinimumSize(new java.awt.Dimension(522, 414));
        setResizable(false);

        instrPanel.setBackground(new java.awt.Color(255, 255, 204));
        instrPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        instr2.setText("<html>&bull Inspect a square on the board by pressing the inspect button on the screen(Lookinglass),<br>   or by pressing E on the keyboard");

        instr4.setText("<html>&bull Some squares have to be interacted with in order to move forward");

        instr3.setText("<html>&bull A square can only be inspected when the inspect button is active (when it is green)");

        instrHeader.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        instrHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        instrHeader.setText("Instructions");

        gotItBtn.setText("Got it!");
        gotItBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gotItBtnActionPerformed(evt);
            }
        });

        instr1.setText("<html>&bull Move the character with the WASD keys");

        instr5.setText("<html>&bull After pressing the inspect button you must choose what to do/say. Some options will<br>advance the game, others are just for fun");

        instr6.setText("<html>&bull Sometimes you need specific items, or to have done a specific thing in order<br>to make an option available");

        javax.swing.GroupLayout instrPanelLayout = new javax.swing.GroupLayout(instrPanel);
        instrPanel.setLayout(instrPanelLayout);
        instrPanelLayout.setHorizontalGroup(
            instrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(instrPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(instrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(instr2)
                    .addComponent(instr4)
                    .addComponent(instr3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(instrHeader, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(instr1)
                    .addComponent(instr5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(instr6))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, instrPanelLayout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(gotItBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(225, 225, 225))
        );
        instrPanelLayout.setVerticalGroup(
            instrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(instrPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(instrHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(instr1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(instr2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(instr3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(instr4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(instr5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(instr6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(gotItBtn)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(instrPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(instrPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gotItBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gotItBtnActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_gotItBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Instructions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Instructions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Instructions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Instructions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Instructions dialog = new Instructions(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton gotItBtn;
    private javax.swing.JLabel instr1;
    private javax.swing.JLabel instr2;
    private javax.swing.JLabel instr3;
    private javax.swing.JLabel instr4;
    private javax.swing.JLabel instr5;
    private javax.swing.JLabel instr6;
    private javax.swing.JLabel instrHeader;
    private javax.swing.JPanel instrPanel;
    // End of variables declaration//GEN-END:variables
}
