/*
 * Kári Snær Kárason - ksk12@hi.is
 * JuggleQuest lokaverkefni - 10/04/2016
 * 
 * Þessi klasi opnast í byrjun leiksins. Hann birtir nafn hans og gefur val á
 * að hefja leik, eða skoða upplýsingar um leikreglur eða gerð leiksins.
 */
package is.hi.Lokaverkefni.vidmot;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;
import javax.swing.Timer;

/**
 *
 * @author Kári
 */
public class MainMenu extends javax.swing.JDialog {
    //timer til að skipta yfir í mynd af logo-i eftir að gif-ið er búið
    private Timer timer;
    private ImageIcon logo = new ImageIcon(getClass().getResource("j8.png"));
    //AdalGluggi adal = new JuggleQuest();
    /**
     * Creates new form MainMenu
     */
    public MainMenu(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        playBtn.setVisible(false);
        instructionsBtn.setVisible(false);
        aboutBtn.setVisible(false);
        
        setDefaultCloseOperation(MainMenu.DISPOSE_ON_CLOSE);
        addWindowListener(new WindowAdapter() {

            @Override
            public void windowClosing(WindowEvent e) {
                System.exit(0);
            }
        });
        //leyfir introi að klárast áður en takkar birtast á main menu
        timer = new Timer(6800, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                    titleLabel.setIcon(logo);
                    playBtn.setVisible(true);
                    instructionsBtn.setVisible(true);
                    aboutBtn.setVisible(true);
            }
        });
        timer.start();
        
        //birtir main menu um leið ef ýtt er á mús
        addMouseListener(new MouseAdapter() {
        @Override public void mouseClicked(MouseEvent e) {
            titleLabel.setIcon(logo);
            playBtn.setVisible(true);
            instructionsBtn.setVisible(true);
            aboutBtn.setVisible(true);
            }
        });
        //birtir main menu um leið ef ýtt er á einhvern takka
        addKeyListener(new KeyAdapter(){
        @Override public void keyPressed(KeyEvent e){
            titleLabel.setIcon(logo);
            playBtn.setVisible(true);
            instructionsBtn.setVisible(true);
            aboutBtn.setVisible(true);
            }
        }); 
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        playBtn = new javax.swing.JButton();
        instructionsBtn = new javax.swing.JButton();
        aboutBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        menuPanel.setBackground(new java.awt.Color(255, 255, 255));
        menuPanel.setMaximumSize(new java.awt.Dimension(640, 420));
        menuPanel.setMinimumSize(new java.awt.Dimension(640, 420));
        menuPanel.setPreferredSize(new java.awt.Dimension(640, 420));

        titleLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/is/hi/Lokaverkefni/vidmot/JQintro2.gif"))); // NOI18N

        playBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/is/hi/Lokaverkefni/vidmot/PlayGameLabel.png"))); // NOI18N
        playBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        playBtn.setMaximumSize(new java.awt.Dimension(100, 23));
        playBtn.setMinimumSize(new java.awt.Dimension(100, 23));
        playBtn.setPreferredSize(new java.awt.Dimension(100, 23));
        playBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playBtnActionPerformed(evt);
            }
        });

        instructionsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/is/hi/Lokaverkefni/vidmot/InstructionsLabel.png"))); // NOI18N
        instructionsBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        instructionsBtn.setMaximumSize(new java.awt.Dimension(100, 23));
        instructionsBtn.setMinimumSize(new java.awt.Dimension(100, 23));
        instructionsBtn.setPreferredSize(new java.awt.Dimension(100, 23));
        instructionsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instructionsBtnActionPerformed(evt);
            }
        });

        aboutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/is/hi/Lokaverkefni/vidmot/AboutLabel.png"))); // NOI18N
        aboutBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        aboutBtn.setMaximumSize(new java.awt.Dimension(100, 23));
        aboutBtn.setMinimumSize(new java.awt.Dimension(100, 23));
        aboutBtn.setPreferredSize(new java.awt.Dimension(100, 23));
        aboutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(playBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(aboutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(instructionsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(titleLabel)
                .addGap(28, 28, 28)
                .addComponent(playBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(instructionsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(aboutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //birtir leikreglur
    private void instructionsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instructionsBtnActionPerformed
        JuggleQuest fg = (JuggleQuest) SwingUtilities.getWindowAncestor(this);
        Instructions instructions = new Instructions(fg,true);
        instructions.setVisible(true);
    }//GEN-LAST:event_instructionsBtnActionPerformed
    //Hefur nýjan leik
    private void playBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playBtnActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_playBtnActionPerformed
    //Birtir upplýsingaglugga
    private void aboutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutBtnActionPerformed
        JuggleQuest fg = (JuggleQuest) SwingUtilities.getWindowAncestor(this);
        About about = new About(fg, true);
        about.setVisible(true);
    }//GEN-LAST:event_aboutBtnActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                MainMenu dialog = new MainMenu(new javax.swing.JFrame(), true);

                dialog.setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutBtn;
    private javax.swing.JButton instructionsBtn;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JButton playBtn;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
